//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsFactura.ServiceReferenceFactura {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cufd", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cufd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idambienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string idambiente {
            get {
                return this.idambienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idambienteField, value) != true)) {
                    this.idambienteField = value;
                    this.RaisePropertyChanged("idambiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string modalidad {
            get {
                return this.modalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.modalidadField, value) != true)) {
                    this.modalidadField = value;
                    this.RaisePropertyChanged("modalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nit {
            get {
                return this.nitField;
            }
            set {
                if ((object.ReferenceEquals(this.nitField, value) != true)) {
                    this.nitField = value;
                    this.RaisePropertyChanged("nit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        private int NumeroFacturaField;
        
        private int CUFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nit {
            get {
                return this.NitField;
            }
            set {
                if ((object.ReferenceEquals(this.NitField, value) != true)) {
                    this.NitField = value;
                    this.RaisePropertyChanged("Nit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NumeroFactura {
            get {
                return this.NumeroFacturaField;
            }
            set {
                if ((this.NumeroFacturaField.Equals(value) != true)) {
                    this.NumeroFacturaField = value;
                    this.RaisePropertyChanged("NumeroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CUF {
            get {
                return this.CUFField;
            }
            set {
                if ((this.CUFField.Equals(value) != true)) {
                    this.CUFField = value;
                    this.RaisePropertyChanged("CUF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TipoDocCliente {
            get {
                return this.TipoDocClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocClienteField, value) != true)) {
                    this.TipoDocClienteField = value;
                    this.RaisePropertyChanged("TipoDocCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NombrCliente {
            get {
                return this.NombrClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrClienteField, value) != true)) {
                    this.NombrClienteField = value;
                    this.RaisePropertyChanged("NombrCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceFactura.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SincronizarFechaHoraResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SincronizarFechaHora", ReplyAction="*")]
        WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraResponse SincronizarFechaHora(WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SincronizarFechaHora", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraResponse> SincronizarFechaHoraAsync(WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idambiente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCufd", ReplyAction="*")]
        WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdResponse ObtenerCufd(WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCufd", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdResponse> ObtenerCufdAsync(WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EmitirFacturaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirFactura", ReplyAction="*")]
        WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaResponse EmitirFactura(WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaResponse> EmitirFacturaAsync(WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SincronizarFechaHoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SincronizarFechaHora", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequestBody Body;
        
        public SincronizarFechaHoraRequest() {
        }
        
        public SincronizarFechaHoraRequest(WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SincronizarFechaHoraRequestBody {
        
        public SincronizarFechaHoraRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SincronizarFechaHoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SincronizarFechaHoraResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraResponseBody Body;
        
        public SincronizarFechaHoraResponse() {
        }
        
        public SincronizarFechaHoraResponse(WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SincronizarFechaHoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SincronizarFechaHoraResult;
        
        public SincronizarFechaHoraResponseBody() {
        }
        
        public SincronizarFechaHoraResponseBody(string SincronizarFechaHoraResult) {
            this.SincronizarFechaHoraResult = SincronizarFechaHoraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCufdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCufd", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequestBody Body;
        
        public ObtenerCufdRequest() {
        }
        
        public ObtenerCufdRequest(WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCufdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idambiente;
        
        public ObtenerCufdRequestBody() {
        }
        
        public ObtenerCufdRequestBody(string idambiente) {
            this.idambiente = idambiente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCufdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCufdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdResponseBody Body;
        
        public ObtenerCufdResponse() {
        }
        
        public ObtenerCufdResponse(WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCufdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsFactura.ServiceReferenceFactura.Cufd ObtenerCufdResult;
        
        public ObtenerCufdResponseBody() {
        }
        
        public ObtenerCufdResponseBody(WindowsFormsFactura.ServiceReferenceFactura.Cufd ObtenerCufdResult) {
            this.ObtenerCufdResult = ObtenerCufdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFactura", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequestBody Body;
        
        public EmitirFacturaRequest() {
        }
        
        public EmitirFacturaRequest(WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NIT;
        
        public EmitirFacturaRequestBody() {
        }
        
        public EmitirFacturaRequestBody(int NIT) {
            this.NIT = NIT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaResponseBody Body;
        
        public EmitirFacturaResponse() {
        }
        
        public EmitirFacturaResponse(WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsFactura.ServiceReferenceFactura.Factura EmitirFacturaResult;
        
        public EmitirFacturaResponseBody() {
        }
        
        public EmitirFacturaResponseBody(WindowsFormsFactura.ServiceReferenceFactura.Factura EmitirFacturaResult) {
            this.EmitirFacturaResult = EmitirFacturaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap>, WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraResponse WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap.SincronizarFechaHora(WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequest request) {
            return base.Channel.SincronizarFechaHora(request);
        }
        
        public string SincronizarFechaHora() {
            WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequest inValue = new WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequest();
            inValue.Body = new WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequestBody();
            WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraResponse retVal = ((WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap)(this)).SincronizarFechaHora(inValue);
            return retVal.Body.SincronizarFechaHoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraResponse> WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap.SincronizarFechaHoraAsync(WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequest request) {
            return base.Channel.SincronizarFechaHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraResponse> SincronizarFechaHoraAsync() {
            WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequest inValue = new WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequest();
            inValue.Body = new WindowsFormsFactura.ServiceReferenceFactura.SincronizarFechaHoraRequestBody();
            return ((WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap)(this)).SincronizarFechaHoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdResponse WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap.ObtenerCufd(WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequest request) {
            return base.Channel.ObtenerCufd(request);
        }
        
        public WindowsFormsFactura.ServiceReferenceFactura.Cufd ObtenerCufd(string idambiente) {
            WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequest inValue = new WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequest();
            inValue.Body = new WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequestBody();
            inValue.Body.idambiente = idambiente;
            WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdResponse retVal = ((WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap)(this)).ObtenerCufd(inValue);
            return retVal.Body.ObtenerCufdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdResponse> WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap.ObtenerCufdAsync(WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequest request) {
            return base.Channel.ObtenerCufdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdResponse> ObtenerCufdAsync(string idambiente) {
            WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequest inValue = new WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequest();
            inValue.Body = new WindowsFormsFactura.ServiceReferenceFactura.ObtenerCufdRequestBody();
            inValue.Body.idambiente = idambiente;
            return ((WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap)(this)).ObtenerCufdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaResponse WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap.EmitirFactura(WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequest request) {
            return base.Channel.EmitirFactura(request);
        }
        
        public WindowsFormsFactura.ServiceReferenceFactura.Factura EmitirFactura(int NIT) {
            WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequest inValue = new WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequest();
            inValue.Body = new WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequestBody();
            inValue.Body.NIT = NIT;
            WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaResponse retVal = ((WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap)(this)).EmitirFactura(inValue);
            return retVal.Body.EmitirFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaResponse> WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap.EmitirFacturaAsync(WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequest request) {
            return base.Channel.EmitirFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaResponse> EmitirFacturaAsync(int NIT) {
            WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequest inValue = new WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequest();
            inValue.Body = new WindowsFormsFactura.ServiceReferenceFactura.EmitirFacturaRequestBody();
            inValue.Body.NIT = NIT;
            return ((WindowsFormsFactura.ServiceReferenceFactura.WebServiceSoap)(this)).EmitirFacturaAsync(inValue);
        }
    }
}
