//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsFactura.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Moneda", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Moneda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string monedaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((object.ReferenceEquals(this.monedaField, value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceBANCOSoap")]
    public interface WebServiceBANCOSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cotizacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerContizacion", ReplyAction="*")]
        WindowsFormsFactura.ServiceReference1.obtenerContizacionResponse obtenerContizacion(WindowsFormsFactura.ServiceReference1.obtenerContizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerContizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReference1.obtenerContizacionResponse> obtenerContizacionAsync(WindowsFormsFactura.ServiceReference1.obtenerContizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerContizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerContizacion", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsFactura.ServiceReference1.obtenerContizacionRequestBody Body;
        
        public obtenerContizacionRequest() {
        }
        
        public obtenerContizacionRequest(WindowsFormsFactura.ServiceReference1.obtenerContizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerContizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cotizacion;
        
        public obtenerContizacionRequestBody() {
        }
        
        public obtenerContizacionRequestBody(string cotizacion) {
            this.cotizacion = cotizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerContizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerContizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsFactura.ServiceReference1.obtenerContizacionResponseBody Body;
        
        public obtenerContizacionResponse() {
        }
        
        public obtenerContizacionResponse(WindowsFormsFactura.ServiceReference1.obtenerContizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerContizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsFactura.ServiceReference1.Moneda obtenerContizacionResult;
        
        public obtenerContizacionResponseBody() {
        }
        
        public obtenerContizacionResponseBody(WindowsFormsFactura.ServiceReference1.Moneda obtenerContizacionResult) {
            this.obtenerContizacionResult = obtenerContizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceBANCOSoapChannel : WindowsFormsFactura.ServiceReference1.WebServiceBANCOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceBANCOSoapClient : System.ServiceModel.ClientBase<WindowsFormsFactura.ServiceReference1.WebServiceBANCOSoap>, WindowsFormsFactura.ServiceReference1.WebServiceBANCOSoap {
        
        public WebServiceBANCOSoapClient() {
        }
        
        public WebServiceBANCOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceBANCOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBANCOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBANCOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsFactura.ServiceReference1.obtenerContizacionResponse WindowsFormsFactura.ServiceReference1.WebServiceBANCOSoap.obtenerContizacion(WindowsFormsFactura.ServiceReference1.obtenerContizacionRequest request) {
            return base.Channel.obtenerContizacion(request);
        }
        
        public WindowsFormsFactura.ServiceReference1.Moneda obtenerContizacion(string cotizacion) {
            WindowsFormsFactura.ServiceReference1.obtenerContizacionRequest inValue = new WindowsFormsFactura.ServiceReference1.obtenerContizacionRequest();
            inValue.Body = new WindowsFormsFactura.ServiceReference1.obtenerContizacionRequestBody();
            inValue.Body.cotizacion = cotizacion;
            WindowsFormsFactura.ServiceReference1.obtenerContizacionResponse retVal = ((WindowsFormsFactura.ServiceReference1.WebServiceBANCOSoap)(this)).obtenerContizacion(inValue);
            return retVal.Body.obtenerContizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReference1.obtenerContizacionResponse> WindowsFormsFactura.ServiceReference1.WebServiceBANCOSoap.obtenerContizacionAsync(WindowsFormsFactura.ServiceReference1.obtenerContizacionRequest request) {
            return base.Channel.obtenerContizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsFactura.ServiceReference1.obtenerContizacionResponse> obtenerContizacionAsync(string cotizacion) {
            WindowsFormsFactura.ServiceReference1.obtenerContizacionRequest inValue = new WindowsFormsFactura.ServiceReference1.obtenerContizacionRequest();
            inValue.Body = new WindowsFormsFactura.ServiceReference1.obtenerContizacionRequestBody();
            inValue.Body.cotizacion = cotizacion;
            return ((WindowsFormsFactura.ServiceReference1.WebServiceBANCOSoap)(this)).obtenerContizacionAsync(inValue);
        }
    }
}
