//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsConsultaSaldo.ServiceReferenceConsulta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int cuentaField;
        
        private float saldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((this.cuentaField.Equals(value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceConsulta.SWConsultaSaldoSoap")]
    public interface SWConsultaSaldoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarResponse Consultar(WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarResponse> ConsultarAsync(WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequestBody Body;
        
        public ConsultarRequest() {
        }
        
        public ConsultarRequest(WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Ncuenta;
        
        public ConsultarRequestBody() {
        }
        
        public ConsultarRequestBody(int Ncuenta) {
            this.Ncuenta = Ncuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarResponseBody Body;
        
        public ConsultarResponse() {
        }
        
        public ConsultarResponse(WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsConsultaSaldo.ServiceReferenceConsulta.Usuario ConsultarResult;
        
        public ConsultarResponseBody() {
        }
        
        public ConsultarResponseBody(WindowsFormsConsultaSaldo.ServiceReferenceConsulta.Usuario ConsultarResult) {
            this.ConsultarResult = ConsultarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWConsultaSaldoSoapChannel : WindowsFormsConsultaSaldo.ServiceReferenceConsulta.SWConsultaSaldoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWConsultaSaldoSoapClient : System.ServiceModel.ClientBase<WindowsFormsConsultaSaldo.ServiceReferenceConsulta.SWConsultaSaldoSoap>, WindowsFormsConsultaSaldo.ServiceReferenceConsulta.SWConsultaSaldoSoap {
        
        public SWConsultaSaldoSoapClient() {
        }
        
        public SWConsultaSaldoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWConsultaSaldoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWConsultaSaldoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWConsultaSaldoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarResponse WindowsFormsConsultaSaldo.ServiceReferenceConsulta.SWConsultaSaldoSoap.Consultar(WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequest request) {
            return base.Channel.Consultar(request);
        }
        
        public WindowsFormsConsultaSaldo.ServiceReferenceConsulta.Usuario Consultar(int Ncuenta) {
            WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequest inValue = new WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequest();
            inValue.Body = new WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequestBody();
            inValue.Body.Ncuenta = Ncuenta;
            WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarResponse retVal = ((WindowsFormsConsultaSaldo.ServiceReferenceConsulta.SWConsultaSaldoSoap)(this)).Consultar(inValue);
            return retVal.Body.ConsultarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarResponse> WindowsFormsConsultaSaldo.ServiceReferenceConsulta.SWConsultaSaldoSoap.ConsultarAsync(WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequest request) {
            return base.Channel.ConsultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarResponse> ConsultarAsync(int Ncuenta) {
            WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequest inValue = new WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequest();
            inValue.Body = new WindowsFormsConsultaSaldo.ServiceReferenceConsulta.ConsultarRequestBody();
            inValue.Body.Ncuenta = Ncuenta;
            return ((WindowsFormsConsultaSaldo.ServiceReferenceConsulta.SWConsultaSaldoSoap)(this)).ConsultarAsync(inValue);
        }
    }
}
