//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsSERECI.SRMatrimonio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_nacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estado_civilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carnet {
            get {
                return this.carnetField;
            }
            set {
                if ((object.ReferenceEquals(this.carnetField, value) != true)) {
                    this.carnetField = value;
                    this.RaisePropertyChanged("carnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primer_ape {
            get {
                return this.primer_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apeField, value) != true)) {
                    this.primer_apeField = value;
                    this.RaisePropertyChanged("primer_ape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundo_ape {
            get {
                return this.segundo_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apeField, value) != true)) {
                    this.segundo_apeField = value;
                    this.RaisePropertyChanged("segundo_ape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_nac {
            get {
                return this.fecha_nacField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_nacField, value) != true)) {
                    this.fecha_nacField = value;
                    this.RaisePropertyChanged("fecha_nac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string estado_civil {
            get {
                return this.estado_civilField;
            }
            set {
                if ((object.ReferenceEquals(this.estado_civilField, value) != true)) {
                    this.estado_civilField = value;
                    this.RaisePropertyChanged("estado_civil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadoNacimiento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CertificadoNacimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_nacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string padreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string madreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carnet {
            get {
                return this.carnetField;
            }
            set {
                if ((object.ReferenceEquals(this.carnetField, value) != true)) {
                    this.carnetField = value;
                    this.RaisePropertyChanged("carnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primer_ape {
            get {
                return this.primer_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apeField, value) != true)) {
                    this.primer_apeField = value;
                    this.RaisePropertyChanged("primer_ape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundo_ape {
            get {
                return this.segundo_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apeField, value) != true)) {
                    this.segundo_apeField = value;
                    this.RaisePropertyChanged("segundo_ape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_nac {
            get {
                return this.fecha_nacField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_nacField, value) != true)) {
                    this.fecha_nacField = value;
                    this.RaisePropertyChanged("fecha_nac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string padre {
            get {
                return this.padreField;
            }
            set {
                if ((object.ReferenceEquals(this.padreField, value) != true)) {
                    this.padreField = value;
                    this.RaisePropertyChanged("padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string madre {
            get {
                return this.madreField;
            }
            set {
                if ((object.ReferenceEquals(this.madreField, value) != true)) {
                    this.madreField = value;
                    this.RaisePropertyChanged("madre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadoMatrimonio", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CertificadoMatrimonio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carnet {
            get {
                return this.carnetField;
            }
            set {
                if ((object.ReferenceEquals(this.carnetField, value) != true)) {
                    this.carnetField = value;
                    this.RaisePropertyChanged("carnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primer_ape {
            get {
                return this.primer_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apeField, value) != true)) {
                    this.primer_apeField = value;
                    this.RaisePropertyChanged("primer_ape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundo_ape {
            get {
                return this.segundo_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apeField, value) != true)) {
                    this.segundo_apeField = value;
                    this.RaisePropertyChanged("segundo_ape");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadoDefuncion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CertificadoDefuncion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_defuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string causaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carnet {
            get {
                return this.carnetField;
            }
            set {
                if ((object.ReferenceEquals(this.carnetField, value) != true)) {
                    this.carnetField = value;
                    this.RaisePropertyChanged("carnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primer_ape {
            get {
                return this.primer_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apeField, value) != true)) {
                    this.primer_apeField = value;
                    this.RaisePropertyChanged("primer_ape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundo_ape {
            get {
                return this.segundo_apeField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apeField, value) != true)) {
                    this.segundo_apeField = value;
                    this.RaisePropertyChanged("segundo_ape");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_defuncion {
            get {
                return this.fecha_defuncionField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_defuncionField, value) != true)) {
                    this.fecha_defuncionField = value;
                    this.RaisePropertyChanged("fecha_defuncion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string causa {
            get {
                return this.causaField;
            }
            set {
                if ((object.ReferenceEquals(this.causaField, value) != true)) {
                    this.causaField = value;
                    this.RaisePropertyChanged("causa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRMatrimonio.SWSEGIPSoap")]
    public interface SWSEGIPSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        WindowsFormsSERECI.SRMatrimonio.ObtenerDatosResponse ObtenerDatos(WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerDatosResponse> ObtenerDatosAsync(WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoResponse ObtenerCertificadoNacimiento(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioResponse ObtenerCertificadoMatrimonio(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDefuncion", ReplyAction="*")]
        WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionResponse ObtenerCertificadoDefuncion(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDefuncion", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest() {
        }
        
        public ObtenerDatosRequest(WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerDatosRequestBody() {
        }
        
        public ObtenerDatosRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse() {
        }
        
        public ObtenerDatosResponse(WindowsFormsSERECI.SRMatrimonio.ObtenerDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.Persona ObtenerDatosResult;
        
        public ObtenerDatosResponseBody() {
        }
        
        public ObtenerDatosResponseBody(WindowsFormsSERECI.SRMatrimonio.Persona ObtenerDatosResult) {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimiento", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequestBody Body;
        
        public ObtenerCertificadoNacimientoRequest() {
        }
        
        public ObtenerCertificadoNacimientoRequest(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerCertificadoNacimientoRequestBody() {
        }
        
        public ObtenerCertificadoNacimientoRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoResponseBody Body;
        
        public ObtenerCertificadoNacimientoResponse() {
        }
        
        public ObtenerCertificadoNacimientoResponse(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.CertificadoNacimiento ObtenerCertificadoNacimientoResult;
        
        public ObtenerCertificadoNacimientoResponseBody() {
        }
        
        public ObtenerCertificadoNacimientoResponseBody(WindowsFormsSERECI.SRMatrimonio.CertificadoNacimiento ObtenerCertificadoNacimientoResult) {
            this.ObtenerCertificadoNacimientoResult = ObtenerCertificadoNacimientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonio", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequestBody Body;
        
        public ObtenerCertificadoMatrimonioRequest() {
        }
        
        public ObtenerCertificadoMatrimonioRequest(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerCertificadoMatrimonioRequestBody() {
        }
        
        public ObtenerCertificadoMatrimonioRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioResponseBody Body;
        
        public ObtenerCertificadoMatrimonioResponse() {
        }
        
        public ObtenerCertificadoMatrimonioResponse(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.CertificadoMatrimonio ObtenerCertificadoMatrimonioResult;
        
        public ObtenerCertificadoMatrimonioResponseBody() {
        }
        
        public ObtenerCertificadoMatrimonioResponseBody(WindowsFormsSERECI.SRMatrimonio.CertificadoMatrimonio ObtenerCertificadoMatrimonioResult) {
            this.ObtenerCertificadoMatrimonioResult = ObtenerCertificadoMatrimonioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncion", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequestBody Body;
        
        public ObtenerCertificadoDefuncionRequest() {
        }
        
        public ObtenerCertificadoDefuncionRequest(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDefuncionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerCertificadoDefuncionRequestBody() {
        }
        
        public ObtenerCertificadoDefuncionRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionResponseBody Body;
        
        public ObtenerCertificadoDefuncionResponse() {
        }
        
        public ObtenerCertificadoDefuncionResponse(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDefuncionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsSERECI.SRMatrimonio.CertificadoDefuncion ObtenerCertificadoDefuncionResult;
        
        public ObtenerCertificadoDefuncionResponseBody() {
        }
        
        public ObtenerCertificadoDefuncionResponseBody(WindowsFormsSERECI.SRMatrimonio.CertificadoDefuncion ObtenerCertificadoDefuncionResult) {
            this.ObtenerCertificadoDefuncionResult = ObtenerCertificadoDefuncionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWSEGIPSoapChannel : WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWSEGIPSoapClient : System.ServiceModel.ClientBase<WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap>, WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap {
        
        public SWSEGIPSoapClient() {
        }
        
        public SWSEGIPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWSEGIPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWSEGIPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWSEGIPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsSERECI.SRMatrimonio.ObtenerDatosResponse WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap.ObtenerDatos(WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatos(request);
        }
        
        public WindowsFormsSERECI.SRMatrimonio.Persona ObtenerDatos(string CI) {
            WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequest inValue = new WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequest();
            inValue.Body = new WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            WindowsFormsSERECI.SRMatrimonio.ObtenerDatosResponse retVal = ((WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerDatosResponse> WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap.ObtenerDatosAsync(WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerDatosResponse> ObtenerDatosAsync(string CI) {
            WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequest inValue = new WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequest();
            inValue.Body = new WindowsFormsSERECI.SRMatrimonio.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            return ((WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoResponse WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap.ObtenerCertificadoNacimiento(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimiento(request);
        }
        
        public WindowsFormsSERECI.SRMatrimonio.CertificadoNacimiento ObtenerCertificadoNacimiento(string CI) {
            WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequest inValue = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.CI = CI;
            WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoResponse retVal = ((WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap)(this)).ObtenerCertificadoNacimiento(inValue);
            return retVal.Body.ObtenerCertificadoNacimientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoResponse> WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap.ObtenerCertificadoNacimientoAsync(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(string CI) {
            WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequest inValue = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.CI = CI;
            return ((WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap)(this)).ObtenerCertificadoNacimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioResponse WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap.ObtenerCertificadoMatrimonio(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequest request) {
            return base.Channel.ObtenerCertificadoMatrimonio(request);
        }
        
        public WindowsFormsSERECI.SRMatrimonio.CertificadoMatrimonio ObtenerCertificadoMatrimonio(string CI) {
            WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequest inValue = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.CI = CI;
            WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioResponse retVal = ((WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap)(this)).ObtenerCertificadoMatrimonio(inValue);
            return retVal.Body.ObtenerCertificadoMatrimonioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioResponse> WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap.ObtenerCertificadoMatrimonioAsync(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequest request) {
            return base.Channel.ObtenerCertificadoMatrimonioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(string CI) {
            WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequest inValue = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.CI = CI;
            return ((WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap)(this)).ObtenerCertificadoMatrimonioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionResponse WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap.ObtenerCertificadoDefuncion(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequest request) {
            return base.Channel.ObtenerCertificadoDefuncion(request);
        }
        
        public WindowsFormsSERECI.SRMatrimonio.CertificadoDefuncion ObtenerCertificadoDefuncion(string CI) {
            WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequest inValue = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body.CI = CI;
            WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionResponse retVal = ((WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap)(this)).ObtenerCertificadoDefuncion(inValue);
            return retVal.Body.ObtenerCertificadoDefuncionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionResponse> WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap.ObtenerCertificadoDefuncionAsync(WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequest request) {
            return base.Channel.ObtenerCertificadoDefuncionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(string CI) {
            WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequest inValue = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new WindowsFormsSERECI.SRMatrimonio.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body.CI = CI;
            return ((WindowsFormsSERECI.SRMatrimonio.SWSEGIPSoap)(this)).ObtenerCertificadoDefuncionAsync(inValue);
        }
    }
}
